text_offset = 0x01120
text_size = 0xEF0
text_address = 0x04001080
rom_file_path = "starfox64.us.rev1.uncompressed.z64"
output_file_path = "rsp/aspMain.cpp"
output_function_name = "aspMain"
extra_indirect_branch_targets = [
0x1104, 0x12CC,
0x11C8, 0x1104,
0x1E78, 0x1554,
0x1EE8, 0x1104,
0x11F8, 0x1104,
0x1284, 0x1B10,
0x1B2C, 0x120C,
0x1D1C, 0x12BC,
0x1804, 0x18B0,
0x1A70, 0x1904,
0x1AD4, 0x1AF8,
0x1A98, 0x1B98,
0x1C48, 0x1C9C,
0x184C, 0x1104,
0x1104, 0x1104,
0x1104, 0x1104
]
